stages:
  - load_dep
  - update_schema
  - build_assets
  - unit_tests
  - sonnar_scan
  - load_dep_client
  - update_schema_client
  - build_assets_client
before_script:
  - "cd /var/www/html/staging/backend"

load_deps:
  stage: load_dep
  tags:
    - gipam
  script: 
    - git pull origin develop
    - composer install
    - yarn install
    - yarn encore production
  only:
    - develop
update_schema:
  stage: update_schema
  tags:
    - gipam
  script: 
    - php bin/console doctrine:schema:update --force
  only:
    - develop    
build_assets:
  stage: build_assets
  tags:
    - gipam
  script:
    - yarn install
    - yarn encore production
  only:
    - develop

load_deps_client:
  stage: load_deps_client
  tags:
    - gipam
  script: 
    - cd /var/www/html/backend
    - git pull origin master
    - composer install
    - yarn install
    - yarn encore production
  only:
    - master
update_schema_client:
  stage: update_schema_client
  tags:
    - gipam
  script: 
    - cd /var/www/html/backend
    - php bin/console doctrine:schema:update --force
  only:
    - master    
build_assets_client:
  stage: build_assets_client
  tags:
    - gipam
  script:
    - cd /var/www/html/backend
    - yarn install
    - yarn encore production
  only:
    - master

unit_tests:
  stage: unit_tests
  tags:
    - gipam
  script:
    - php bin/console d:d:d --force --env=test
    - php bin/console d:d:c --env=test
    - php bin/console d:s:u --force --env=test
    - ./vendor/bin/codecept clean
    - ./vendor/bin/codecept run api,unit --coverage --coverage-xml --xml --fail-fast
  when: manual    
  only:
    - develop
sonnar_scan:
  stage: sonnar_scan
  tags:
    - gipam
  script:
    - /opt/sonar-scanner/bin/sonar-scanner
  when: manual    
  only:
    - develop 	
variables:
  GIT_STRATEGY: clone
