variables:
  GIT_STRATEGY: none

stages:
  - deploy
  - packaging

Deploy INTERN:
  stage: deploy
  tags:
    - GIPAM-backend
  script:
    - cd /var/www/html/staging/gipam-backend/
    - git pull origin develop
    - composer install
    - php7.4  bin/console c:c --env=dev
    - php7.4  bin/console c:w --env=dev
  only:
    - develop

Deploy Recette:
  stage: deploy
  tags:
    - GIPAM-backend
  script:
    - cd /var/www/html/gipam-backend/
    - sh gitlab-ci-update.sh develop dev php7.4
  only:
    - recette

Build Delivrable Package:
  artifacts:
    when: on_success
    name: "gipam-backend-build-$CI_COMMIT_TAG-$CI_JOB_ID"
    paths:
      - "build/gipam-backend-${CI_COMMIT_TAG}-$(date +'%Y-%m-%d').tar.gz"
  variables:
    GIT_STRATEGY: clone
    APP_ENV: prod
  only:
    - tags
  stage: packaging
  tags:
    - GIPAM-backend
  script:
    - composer install
    - rm -rf var/cache/*
    - rm -rf var/log/*
    - rm -rf .env.test .gitignore .gitlab-ci.yml gitlab-ci-update.sh phpunit.xml.dist
    - cd ../
    - tar --exclude='.git' -czf "gipam-backend-${CI_COMMIT_TAG}-$(date +'%Y-%m-%d').tar.gz" gipam-backend/
    - mkdir gipam-backend/build/
    - mv "gipam-backend-${CI_COMMIT_TAG}-$(date +'%Y-%m-%d').tar.gz" gipam-backend/build/
