stages:
  - load_dep
  - update_schema
  - build_assets
  - unit_tests
  - sonnar_scan

before_script:
  - "cd /var/www/html/backend"
  - whoami
  - pwd
  - git pull origin develop

load_deps:
  stage: load_dep
  tags:
    - gipam
  script: 
    - composer install
  only:
    - develop
update_schema:
  stage: update_schema
  tags:
    - gipam
  script: 
    - php bin/console doctrine:schema:update --force
  only:
    - develop    
build_assets:
  stage: build_assets
  tags:
    - gipam
  script:
    - yarn install
    - yarn encore production
  only:
    - dev

unit_tests:
  stage: unit_tests
  tags:
    - gipam
  script:
    - php bin/console d:d:d --force --env=test
    - php bin/console d:d:c --env=test
    - php bin/console d:s:u --force --env=test
    - ./vendor/bin/codecept clean
    - ./vendor/bin/codecept run api,unit --coverage --coverage-xml --xml --fail-fast
  when: manual    
  only:
    - develop
sonnar_scan:
  stage: sonnar_scan
  tags:
    - gipam
  script:
    - /opt/sonar-scanner/bin/sonar-scanner
  when: manual    
  only:
    - develop 	
variables:
  GIT_STRATEGY: clone
