<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210413120955 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE action_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE alerte_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE auteur_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE batiment_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE categorie_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE commune_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE constat_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE correspondant_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE denomination_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE departement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE deposant_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE domaine_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE epoque_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE etablissement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE fichier_joint_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE localisation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE log_ouvre_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE matiere_technique_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ministere_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mode_entree_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mouvement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE objet_mobilier_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE piece_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE region_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE responsable_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE service_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE site_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE sous_direction_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE sous_type_constat_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE style_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_auteur_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_constat_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_constat_action_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_deposant_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_etablissement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_localisation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_mouvement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_mouvement_action_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE user_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE action (id INT NOT NULL, type_id INT DEFAULT NULL, mouvement_id INT DEFAULT NULL, type_mouvement_action_id INT DEFAULT NULL, constat_id INT DEFAULT NULL, commentaire TEXT DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delai INT NOT NULL, nature_action VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_47CC8C92C54C8C93 ON action (type_id)');
        $this->addSql('CREATE INDEX IDX_47CC8C92ECD1C222 ON action (mouvement_id)');
        $this->addSql('CREATE INDEX IDX_47CC8C92E8BC2E97 ON action (type_mouvement_action_id)');
        $this->addSql('CREATE INDEX IDX_47CC8C92BDDDB8C ON action (constat_id)');
        $this->addSql('CREATE TABLE alerte (id INT NOT NULL, action_id INT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3AE753A9D32F035 ON alerte (action_id)');
        $this->addSql('CREATE TABLE auteur (id INT NOT NULL, prenom VARCHAR(255) DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE batiment (id INT NOT NULL, site_id INT DEFAULT NULL, commune_id INT DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, addresse VARCHAR(255) DEFAULT NULL, distrib VARCHAR(255) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_disparition TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cedex VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F5FAB00CF6BD1646 ON batiment (site_id)');
        $this->addSql('CREATE INDEX IDX_F5FAB00C131A4F72 ON batiment (commune_id)');
        $this->addSql('CREATE TABLE categorie (id INT NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE commune (id INT NOT NULL, departement_id INT DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E2E2D1EECCF9E01E ON commune (departement_id)');
        $this->addSql('CREATE TABLE constat (id INT NOT NULL, sous_type_constat_id INT DEFAULT NULL, objet_mobilier_id INT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, commentaire TEXT DEFAULT NULL, titre_perception BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F96EDD98DAAF40C5 ON constat (sous_type_constat_id)');
        $this->addSql('CREATE INDEX IDX_F96EDD98B7105527 ON constat (objet_mobilier_id)');
        $this->addSql('CREATE TABLE correspondant (id INT NOT NULL, etablissement_id INT DEFAULT NULL, sous_direction_id INT DEFAULT NULL, service_id INT DEFAULT NULL, prenom VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, telephone VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E4DD79A3FF631228 ON correspondant (etablissement_id)');
        $this->addSql('CREATE INDEX IDX_E4DD79A310E381F2 ON correspondant (sous_direction_id)');
        $this->addSql('CREATE INDEX IDX_E4DD79A3ED5CA9E6 ON correspondant (service_id)');
        $this->addSql('CREATE TABLE denomination (id INT NOT NULL, domaine_id INT DEFAULT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_15AEA10C4272FC9F ON denomination (domaine_id)');
        $this->addSql('CREATE TABLE denomination_matiere_technique (denomination_id INT NOT NULL, matiere_technique_id INT NOT NULL, PRIMARY KEY(denomination_id, matiere_technique_id))');
        $this->addSql('CREATE INDEX IDX_CD45773AE9293F06 ON denomination_matiere_technique (denomination_id)');
        $this->addSql('CREATE INDEX IDX_CD45773A5564D221 ON denomination_matiere_technique (matiere_technique_id)');
        $this->addSql('CREATE TABLE departement (id INT NOT NULL, region_id INT DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_disparition TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C1765B6398260155 ON departement (region_id)');
        $this->addSql('CREATE TABLE deposant (id INT NOT NULL, type_deposant_id INT DEFAULT NULL, sigle VARCHAR(255) DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, adresse VARCHAR(255) DEFAULT NULL, ville VARCHAR(255) DEFAULT NULL, departement VARCHAR(255) DEFAULT NULL, distrib VARCHAR(255) DEFAULT NULL, tel VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, contact VARCHAR(255) DEFAULT NULL, commentaire TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_64C4A25E4B42C9BD ON deposant (type_deposant_id)');
        $this->addSql('CREATE TABLE domaine (id INT NOT NULL, libelle VARCHAR(255) DEFAULT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE epoque (id INT NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE etablissement (id INT NOT NULL, ministere_id INT DEFAULT NULL, type_id INT DEFAULT NULL, libelle VARCHAR(255) DEFAULT NULL, sigle VARCHAR(255) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_disparition TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_20FD592CAD745416 ON etablissement (ministere_id)');
        $this->addSql('CREATE INDEX IDX_20FD592CC54C8C93 ON etablissement (type_id)');
        $this->addSql('CREATE TABLE fichier_joint (id INT NOT NULL, objet_mobilier_id INT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, commentaire TEXT DEFAULT NULL, lien VARCHAR(255) NOT NULL, image_principale BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AAACC83FB7105527 ON fichier_joint (objet_mobilier_id)');
        $this->addSql('CREATE TABLE localisation (id INT NOT NULL, etablissement_id INT DEFAULT NULL, sous_direction_id INT DEFAULT NULL, type_id INT DEFAULT NULL, piece_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BFD3CE8FFF631228 ON localisation (etablissement_id)');
        $this->addSql('CREATE INDEX IDX_BFD3CE8F10E381F2 ON localisation (sous_direction_id)');
        $this->addSql('CREATE INDEX IDX_BFD3CE8FC54C8C93 ON localisation (type_id)');
        $this->addSql('CREATE INDEX IDX_BFD3CE8FC40FCFA8 ON localisation (piece_id)');
        $this->addSql('CREATE TABLE log_ouvre (id INT NOT NULL, objet_mobilier_id INT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D1723633B7105527 ON log_ouvre (objet_mobilier_id)');
        $this->addSql('CREATE TABLE matiere_technique (id INT NOT NULL, libelle VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE ministere (id INT NOT NULL, nom VARCHAR(255) DEFAULT NULL, sigle VARCHAR(255) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_disparition TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE mobilier_bureau (id INT NOT NULL, fournisseur VARCHAR(255) DEFAULT NULL, prix_achat DOUBLE PRECISION DEFAULT NULL, etat VARCHAR(255) DEFAULT NULL, volume_unitaire DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE mode_entree (id INT NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE mouvement (id INT NOT NULL, localisation_id INT DEFAULT NULL, type_id INT DEFAULT NULL, objet_mobilier_id INT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, commentaire TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5B51FC3EC68BE09C ON mouvement (localisation_id)');
        $this->addSql('CREATE INDEX IDX_5B51FC3EC54C8C93 ON mouvement (type_id)');
        $this->addSql('CREATE INDEX IDX_5B51FC3EB7105527 ON mouvement (objet_mobilier_id)');
        $this->addSql('CREATE TABLE mouvement_correspondant (mouvement_id INT NOT NULL, correspondant_id INT NOT NULL, PRIMARY KEY(mouvement_id, correspondant_id))');
        $this->addSql('CREATE INDEX IDX_57A584D2ECD1C222 ON mouvement_correspondant (mouvement_id)');
        $this->addSql('CREATE INDEX IDX_57A584D2BBE04A3B ON mouvement_correspondant (correspondant_id)');
        $this->addSql('CREATE TABLE objet_mobilier (id INT NOT NULL, epoque_id INT DEFAULT NULL, style_id INT DEFAULT NULL, matiere_technique_id INT DEFAULT NULL, denomination_id INT DEFAULT NULL, domaine_id INT DEFAULT NULL, status_id INT DEFAULT NULL, titre VARCHAR(255) DEFAULT NULL, longueur DOUBLE PRECISION DEFAULT NULL, largeur DOUBLE PRECISION DEFAULT NULL, hauteur DOUBLE PRECISION DEFAULT NULL, profondeur DOUBLE PRECISION DEFAULT NULL, diametre DOUBLE PRECISION DEFAULT NULL, poids DOUBLE PRECISION DEFAULT NULL, nombre_unite INT DEFAULT NULL, description_commentaire TEXT DEFAULT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A38B3DB645E7D711 ON objet_mobilier (epoque_id)');
        $this->addSql('CREATE INDEX IDX_A38B3DB6BACD6074 ON objet_mobilier (style_id)');
        $this->addSql('CREATE INDEX IDX_A38B3DB65564D221 ON objet_mobilier (matiere_technique_id)');
        $this->addSql('CREATE INDEX IDX_A38B3DB6E9293F06 ON objet_mobilier (denomination_id)');
        $this->addSql('CREATE INDEX IDX_A38B3DB64272FC9F ON objet_mobilier (domaine_id)');
        $this->addSql('CREATE INDEX IDX_A38B3DB66BF700BD ON objet_mobilier (status_id)');
        $this->addSql('CREATE TABLE objet_mobilier_auteur (objet_mobilier_id INT NOT NULL, auteur_id INT NOT NULL, PRIMARY KEY(objet_mobilier_id, auteur_id))');
        $this->addSql('CREATE INDEX IDX_9EC00F42B7105527 ON objet_mobilier_auteur (objet_mobilier_id)');
        $this->addSql('CREATE INDEX IDX_9EC00F4260BB6FE6 ON objet_mobilier_auteur (auteur_id)');
        $this->addSql('CREATE TABLE ouvre_art (id INT NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, longueur_totale DOUBLE PRECISION DEFAULT NULL, largeur_totale DOUBLE PRECISION DEFAULT NULL, hauteur_totale DOUBLE PRECISION DEFAULT NULL, signature_inscription VARCHAR(255) DEFAULT NULL, mots_descriptifs VARCHAR(255) DEFAULT NULL, valeur_assurance INT DEFAULT NULL, date_valeur_assurance TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_depot TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, numero_arret INT DEFAULT NULL, autres_inscription VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE piece (id INT NOT NULL, batiment_id INT DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, niveau VARCHAR(255) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_44CA0B23D6F6891B ON piece (batiment_id)');
        $this->addSql('CREATE TABLE region (id INT NOT NULL, nom VARCHAR(255) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_disparition TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE responsable (id INT NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE responsable_batiment (responsable_id INT NOT NULL, batiment_id INT NOT NULL, PRIMARY KEY(responsable_id, batiment_id))');
        $this->addSql('CREATE INDEX IDX_D152DC1653C59D72 ON responsable_batiment (responsable_id)');
        $this->addSql('CREATE INDEX IDX_D152DC16D6F6891B ON responsable_batiment (batiment_id)');
        $this->addSql('CREATE TABLE service (id INT NOT NULL, sous_direction_id INT DEFAULT NULL, libelle VARCHAR(255) DEFAULT NULL, sigle VARCHAR(255) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_disparition TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E19D9AD210E381F2 ON service (sous_direction_id)');
        $this->addSql('CREATE TABLE site (id INT NOT NULL, libelle VARCHAR(255) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_disparition TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE sous_direction (id INT NOT NULL, etablissement_id INT DEFAULT NULL, libelle VARCHAR(255) DEFAULT NULL, sigle VARCHAR(255) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_25433AFCFF631228 ON sous_direction (etablissement_id)');
        $this->addSql('CREATE TABLE sous_type_constat (id INT NOT NULL, type_constat_id INT DEFAULT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6EDFEA0816DE0DA9 ON sous_type_constat (type_constat_id)');
        $this->addSql('CREATE TABLE status (id INT NOT NULL, type VARCHAR(255) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, commentaire TEXT DEFAULT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE statut_depot (id INT NOT NULL, deposant_id INT DEFAULT NULL, numero_inventaire INT DEFAULT NULL, date_depot TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7569E4C25B1E2C ON statut_depot (deposant_id)');
        $this->addSql('CREATE TABLE statut_propriete (id INT NOT NULL, mode_entree_id INT DEFAULT NULL, categorie_id INT DEFAULT NULL, date_entree TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, marquage VARCHAR(255) DEFAULT NULL, propUnPourCent BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D206CE51C8A5F4A8 ON statut_propriete (mode_entree_id)');
        $this->addSql('CREATE INDEX IDX_D206CE51BCF5E72D ON statut_propriete (categorie_id)');
        $this->addSql('CREATE TABLE style (id INT NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_auteur (id INT NOT NULL, auteur_id INT DEFAULT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_268DDA7860BB6FE6 ON type_auteur (auteur_id)');
        $this->addSql('CREATE TABLE type_constat (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_constat_action (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_deposant (id INT NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_etablissement (id INT NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_localisation (id INT NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_mouvement (id INT NOT NULL, libelle VARCHAR(150) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_mouvement_action (id INT NOT NULL, type_mouvement_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6A1383156B927827 ON type_mouvement_action (type_mouvement_id)');
        $this->addSql('CREATE TABLE "user" (id INT NOT NULL, username VARCHAR(50) NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, password VARCHAR(100) DEFAULT NULL, roles TEXT DEFAULT NULL, comment TEXT DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('COMMENT ON COLUMN "user".roles IS \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE action ADD CONSTRAINT FK_47CC8C92C54C8C93 FOREIGN KEY (type_id) REFERENCES type_constat_action (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE action ADD CONSTRAINT FK_47CC8C92ECD1C222 FOREIGN KEY (mouvement_id) REFERENCES mouvement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE action ADD CONSTRAINT FK_47CC8C92E8BC2E97 FOREIGN KEY (type_mouvement_action_id) REFERENCES type_mouvement_action (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE action ADD CONSTRAINT FK_47CC8C92BDDDB8C FOREIGN KEY (constat_id) REFERENCES constat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE alerte ADD CONSTRAINT FK_3AE753A9D32F035 FOREIGN KEY (action_id) REFERENCES action (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE batiment ADD CONSTRAINT FK_F5FAB00CF6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE batiment ADD CONSTRAINT FK_F5FAB00C131A4F72 FOREIGN KEY (commune_id) REFERENCES commune (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commune ADD CONSTRAINT FK_E2E2D1EECCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE constat ADD CONSTRAINT FK_F96EDD98DAAF40C5 FOREIGN KEY (sous_type_constat_id) REFERENCES sous_type_constat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE constat ADD CONSTRAINT FK_F96EDD98B7105527 FOREIGN KEY (objet_mobilier_id) REFERENCES objet_mobilier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE correspondant ADD CONSTRAINT FK_E4DD79A3FF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE correspondant ADD CONSTRAINT FK_E4DD79A310E381F2 FOREIGN KEY (sous_direction_id) REFERENCES sous_direction (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE correspondant ADD CONSTRAINT FK_E4DD79A3ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE denomination ADD CONSTRAINT FK_15AEA10C4272FC9F FOREIGN KEY (domaine_id) REFERENCES domaine (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE denomination_matiere_technique ADD CONSTRAINT FK_CD45773AE9293F06 FOREIGN KEY (denomination_id) REFERENCES denomination (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE denomination_matiere_technique ADD CONSTRAINT FK_CD45773A5564D221 FOREIGN KEY (matiere_technique_id) REFERENCES matiere_technique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE departement ADD CONSTRAINT FK_C1765B6398260155 FOREIGN KEY (region_id) REFERENCES region (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deposant ADD CONSTRAINT FK_64C4A25E4B42C9BD FOREIGN KEY (type_deposant_id) REFERENCES type_deposant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE etablissement ADD CONSTRAINT FK_20FD592CAD745416 FOREIGN KEY (ministere_id) REFERENCES ministere (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE etablissement ADD CONSTRAINT FK_20FD592CC54C8C93 FOREIGN KEY (type_id) REFERENCES type_etablissement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fichier_joint ADD CONSTRAINT FK_AAACC83FB7105527 FOREIGN KEY (objet_mobilier_id) REFERENCES objet_mobilier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localisation ADD CONSTRAINT FK_BFD3CE8FFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localisation ADD CONSTRAINT FK_BFD3CE8F10E381F2 FOREIGN KEY (sous_direction_id) REFERENCES sous_direction (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localisation ADD CONSTRAINT FK_BFD3CE8FC54C8C93 FOREIGN KEY (type_id) REFERENCES type_localisation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localisation ADD CONSTRAINT FK_BFD3CE8FC40FCFA8 FOREIGN KEY (piece_id) REFERENCES piece (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE log_ouvre ADD CONSTRAINT FK_D1723633B7105527 FOREIGN KEY (objet_mobilier_id) REFERENCES objet_mobilier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mobilier_bureau ADD CONSTRAINT FK_9573A921BF396750 FOREIGN KEY (id) REFERENCES objet_mobilier (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mouvement ADD CONSTRAINT FK_5B51FC3EC68BE09C FOREIGN KEY (localisation_id) REFERENCES localisation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mouvement ADD CONSTRAINT FK_5B51FC3EC54C8C93 FOREIGN KEY (type_id) REFERENCES type_mouvement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mouvement ADD CONSTRAINT FK_5B51FC3EB7105527 FOREIGN KEY (objet_mobilier_id) REFERENCES objet_mobilier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mouvement_correspondant ADD CONSTRAINT FK_57A584D2ECD1C222 FOREIGN KEY (mouvement_id) REFERENCES mouvement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mouvement_correspondant ADD CONSTRAINT FK_57A584D2BBE04A3B FOREIGN KEY (correspondant_id) REFERENCES correspondant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE objet_mobilier ADD CONSTRAINT FK_A38B3DB645E7D711 FOREIGN KEY (epoque_id) REFERENCES epoque (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE objet_mobilier ADD CONSTRAINT FK_A38B3DB6BACD6074 FOREIGN KEY (style_id) REFERENCES style (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE objet_mobilier ADD CONSTRAINT FK_A38B3DB65564D221 FOREIGN KEY (matiere_technique_id) REFERENCES matiere_technique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE objet_mobilier ADD CONSTRAINT FK_A38B3DB6E9293F06 FOREIGN KEY (denomination_id) REFERENCES denomination (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE objet_mobilier ADD CONSTRAINT FK_A38B3DB64272FC9F FOREIGN KEY (domaine_id) REFERENCES domaine (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE objet_mobilier ADD CONSTRAINT FK_A38B3DB66BF700BD FOREIGN KEY (status_id) REFERENCES status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE objet_mobilier_auteur ADD CONSTRAINT FK_9EC00F42B7105527 FOREIGN KEY (objet_mobilier_id) REFERENCES objet_mobilier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE objet_mobilier_auteur ADD CONSTRAINT FK_9EC00F4260BB6FE6 FOREIGN KEY (auteur_id) REFERENCES auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ouvre_art ADD CONSTRAINT FK_89F9647BBF396750 FOREIGN KEY (id) REFERENCES objet_mobilier (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE piece ADD CONSTRAINT FK_44CA0B23D6F6891B FOREIGN KEY (batiment_id) REFERENCES batiment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE responsable_batiment ADD CONSTRAINT FK_D152DC1653C59D72 FOREIGN KEY (responsable_id) REFERENCES responsable (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE responsable_batiment ADD CONSTRAINT FK_D152DC16D6F6891B FOREIGN KEY (batiment_id) REFERENCES batiment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD210E381F2 FOREIGN KEY (sous_direction_id) REFERENCES sous_direction (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sous_direction ADD CONSTRAINT FK_25433AFCFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sous_type_constat ADD CONSTRAINT FK_6EDFEA0816DE0DA9 FOREIGN KEY (type_constat_id) REFERENCES type_constat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE statut_depot ADD CONSTRAINT FK_7569E4C25B1E2C FOREIGN KEY (deposant_id) REFERENCES deposant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE statut_depot ADD CONSTRAINT FK_7569E4C2BF396750 FOREIGN KEY (id) REFERENCES status (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE statut_propriete ADD CONSTRAINT FK_D206CE51C8A5F4A8 FOREIGN KEY (mode_entree_id) REFERENCES mode_entree (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE statut_propriete ADD CONSTRAINT FK_D206CE51BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE statut_propriete ADD CONSTRAINT FK_D206CE51BF396750 FOREIGN KEY (id) REFERENCES status (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE type_auteur ADD CONSTRAINT FK_268DDA7860BB6FE6 FOREIGN KEY (auteur_id) REFERENCES auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE type_mouvement_action ADD CONSTRAINT FK_6A1383156B927827 FOREIGN KEY (type_mouvement_id) REFERENCES type_mouvement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE alerte DROP CONSTRAINT FK_3AE753A9D32F035');
        $this->addSql('ALTER TABLE objet_mobilier_auteur DROP CONSTRAINT FK_9EC00F4260BB6FE6');
        $this->addSql('ALTER TABLE type_auteur DROP CONSTRAINT FK_268DDA7860BB6FE6');
        $this->addSql('ALTER TABLE piece DROP CONSTRAINT FK_44CA0B23D6F6891B');
        $this->addSql('ALTER TABLE responsable_batiment DROP CONSTRAINT FK_D152DC16D6F6891B');
        $this->addSql('ALTER TABLE statut_propriete DROP CONSTRAINT FK_D206CE51BCF5E72D');
        $this->addSql('ALTER TABLE batiment DROP CONSTRAINT FK_F5FAB00C131A4F72');
        $this->addSql('ALTER TABLE action DROP CONSTRAINT FK_47CC8C92BDDDB8C');
        $this->addSql('ALTER TABLE mouvement_correspondant DROP CONSTRAINT FK_57A584D2BBE04A3B');
        $this->addSql('ALTER TABLE denomination_matiere_technique DROP CONSTRAINT FK_CD45773AE9293F06');
        $this->addSql('ALTER TABLE objet_mobilier DROP CONSTRAINT FK_A38B3DB6E9293F06');
        $this->addSql('ALTER TABLE commune DROP CONSTRAINT FK_E2E2D1EECCF9E01E');
        $this->addSql('ALTER TABLE statut_depot DROP CONSTRAINT FK_7569E4C25B1E2C');
        $this->addSql('ALTER TABLE denomination DROP CONSTRAINT FK_15AEA10C4272FC9F');
        $this->addSql('ALTER TABLE objet_mobilier DROP CONSTRAINT FK_A38B3DB64272FC9F');
        $this->addSql('ALTER TABLE objet_mobilier DROP CONSTRAINT FK_A38B3DB645E7D711');
        $this->addSql('ALTER TABLE correspondant DROP CONSTRAINT FK_E4DD79A3FF631228');
        $this->addSql('ALTER TABLE localisation DROP CONSTRAINT FK_BFD3CE8FFF631228');
        $this->addSql('ALTER TABLE sous_direction DROP CONSTRAINT FK_25433AFCFF631228');
        $this->addSql('ALTER TABLE mouvement DROP CONSTRAINT FK_5B51FC3EC68BE09C');
        $this->addSql('ALTER TABLE denomination_matiere_technique DROP CONSTRAINT FK_CD45773A5564D221');
        $this->addSql('ALTER TABLE objet_mobilier DROP CONSTRAINT FK_A38B3DB65564D221');
        $this->addSql('ALTER TABLE etablissement DROP CONSTRAINT FK_20FD592CAD745416');
        $this->addSql('ALTER TABLE statut_propriete DROP CONSTRAINT FK_D206CE51C8A5F4A8');
        $this->addSql('ALTER TABLE action DROP CONSTRAINT FK_47CC8C92ECD1C222');
        $this->addSql('ALTER TABLE mouvement_correspondant DROP CONSTRAINT FK_57A584D2ECD1C222');
        $this->addSql('ALTER TABLE constat DROP CONSTRAINT FK_F96EDD98B7105527');
        $this->addSql('ALTER TABLE fichier_joint DROP CONSTRAINT FK_AAACC83FB7105527');
        $this->addSql('ALTER TABLE log_ouvre DROP CONSTRAINT FK_D1723633B7105527');
        $this->addSql('ALTER TABLE mobilier_bureau DROP CONSTRAINT FK_9573A921BF396750');
        $this->addSql('ALTER TABLE mouvement DROP CONSTRAINT FK_5B51FC3EB7105527');
        $this->addSql('ALTER TABLE objet_mobilier_auteur DROP CONSTRAINT FK_9EC00F42B7105527');
        $this->addSql('ALTER TABLE ouvre_art DROP CONSTRAINT FK_89F9647BBF396750');
        $this->addSql('ALTER TABLE localisation DROP CONSTRAINT FK_BFD3CE8FC40FCFA8');
        $this->addSql('ALTER TABLE departement DROP CONSTRAINT FK_C1765B6398260155');
        $this->addSql('ALTER TABLE responsable_batiment DROP CONSTRAINT FK_D152DC1653C59D72');
        $this->addSql('ALTER TABLE correspondant DROP CONSTRAINT FK_E4DD79A3ED5CA9E6');
        $this->addSql('ALTER TABLE batiment DROP CONSTRAINT FK_F5FAB00CF6BD1646');
        $this->addSql('ALTER TABLE correspondant DROP CONSTRAINT FK_E4DD79A310E381F2');
        $this->addSql('ALTER TABLE localisation DROP CONSTRAINT FK_BFD3CE8F10E381F2');
        $this->addSql('ALTER TABLE service DROP CONSTRAINT FK_E19D9AD210E381F2');
        $this->addSql('ALTER TABLE constat DROP CONSTRAINT FK_F96EDD98DAAF40C5');
        $this->addSql('ALTER TABLE objet_mobilier DROP CONSTRAINT FK_A38B3DB66BF700BD');
        $this->addSql('ALTER TABLE statut_depot DROP CONSTRAINT FK_7569E4C2BF396750');
        $this->addSql('ALTER TABLE statut_propriete DROP CONSTRAINT FK_D206CE51BF396750');
        $this->addSql('ALTER TABLE objet_mobilier DROP CONSTRAINT FK_A38B3DB6BACD6074');
        $this->addSql('ALTER TABLE sous_type_constat DROP CONSTRAINT FK_6EDFEA0816DE0DA9');
        $this->addSql('ALTER TABLE action DROP CONSTRAINT FK_47CC8C92C54C8C93');
        $this->addSql('ALTER TABLE deposant DROP CONSTRAINT FK_64C4A25E4B42C9BD');
        $this->addSql('ALTER TABLE etablissement DROP CONSTRAINT FK_20FD592CC54C8C93');
        $this->addSql('ALTER TABLE localisation DROP CONSTRAINT FK_BFD3CE8FC54C8C93');
        $this->addSql('ALTER TABLE mouvement DROP CONSTRAINT FK_5B51FC3EC54C8C93');
        $this->addSql('ALTER TABLE type_mouvement_action DROP CONSTRAINT FK_6A1383156B927827');
        $this->addSql('ALTER TABLE action DROP CONSTRAINT FK_47CC8C92E8BC2E97');
        $this->addSql('DROP SEQUENCE action_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE alerte_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE auteur_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE batiment_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE categorie_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE commune_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE constat_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE correspondant_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE denomination_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE departement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE deposant_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE domaine_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE epoque_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE etablissement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE fichier_joint_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE localisation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE log_ouvre_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE matiere_technique_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ministere_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE mode_entree_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE mouvement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE objet_mobilier_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE piece_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE region_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE responsable_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE service_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE site_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE sous_direction_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE sous_type_constat_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE style_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_auteur_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_constat_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_constat_action_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_deposant_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_etablissement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_localisation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_mouvement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_mouvement_action_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE user_id_seq CASCADE');
        $this->addSql('DROP TABLE action');
        $this->addSql('DROP TABLE alerte');
        $this->addSql('DROP TABLE auteur');
        $this->addSql('DROP TABLE batiment');
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE commune');
        $this->addSql('DROP TABLE constat');
        $this->addSql('DROP TABLE correspondant');
        $this->addSql('DROP TABLE denomination');
        $this->addSql('DROP TABLE denomination_matiere_technique');
        $this->addSql('DROP TABLE departement');
        $this->addSql('DROP TABLE deposant');
        $this->addSql('DROP TABLE domaine');
        $this->addSql('DROP TABLE epoque');
        $this->addSql('DROP TABLE etablissement');
        $this->addSql('DROP TABLE fichier_joint');
        $this->addSql('DROP TABLE localisation');
        $this->addSql('DROP TABLE log_ouvre');
        $this->addSql('DROP TABLE matiere_technique');
        $this->addSql('DROP TABLE ministere');
        $this->addSql('DROP TABLE mobilier_bureau');
        $this->addSql('DROP TABLE mode_entree');
        $this->addSql('DROP TABLE mouvement');
        $this->addSql('DROP TABLE mouvement_correspondant');
        $this->addSql('DROP TABLE objet_mobilier');
        $this->addSql('DROP TABLE objet_mobilier_auteur');
        $this->addSql('DROP TABLE ouvre_art');
        $this->addSql('DROP TABLE piece');
        $this->addSql('DROP TABLE region');
        $this->addSql('DROP TABLE responsable');
        $this->addSql('DROP TABLE responsable_batiment');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE site');
        $this->addSql('DROP TABLE sous_direction');
        $this->addSql('DROP TABLE sous_type_constat');
        $this->addSql('DROP TABLE status');
        $this->addSql('DROP TABLE statut_depot');
        $this->addSql('DROP TABLE statut_propriete');
        $this->addSql('DROP TABLE style');
        $this->addSql('DROP TABLE type_auteur');
        $this->addSql('DROP TABLE type_constat');
        $this->addSql('DROP TABLE type_constat_action');
        $this->addSql('DROP TABLE type_deposant');
        $this->addSql('DROP TABLE type_etablissement');
        $this->addSql('DROP TABLE type_localisation');
        $this->addSql('DROP TABLE type_mouvement');
        $this->addSql('DROP TABLE type_mouvement_action');
        $this->addSql('DROP TABLE "user"');
    }
}
