login_check:
  path:     /api/login_check
  methods:  [POST]
#web_controllers:
#  resource: ../../src/Controller/WEB
#  type: annotation
api_controllers:
  resource: ../src/Controller/API
  type: annotation
  prefix: /api
  name_prefix: api_
kernel:
  resource: ../src/Kernel.php
  type: annotation
# config/routes.yaml
app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
# config/routes.yaml
app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }