<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210319133954 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE action_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE action_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE alert_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE art_work_log_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE attachment_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE author_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE author_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE building_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE commune_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE correspondent_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE denomination_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE departement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE deposit_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE depositor_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE entry_mode_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE era_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE establishment_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE establishment_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE field_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE furniture_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE location_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE location_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material_technique_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ministry_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE movement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE movement_action_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE movement_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE property_status_category_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE region_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE report_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE report_sub_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE report_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE responsible_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE room_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE service_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE site_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE style_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE sub_division_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE user_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE action (id INT NOT NULL, type_id INT DEFAULT NULL, movement_action_type_id INT DEFAULT NULL, report_id INT DEFAULT NULL, comment TEXT DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, period INT NOT NULL, action_nature VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_47CC8C92C54C8C93 ON action (type_id)');
        $this->addSql('CREATE INDEX IDX_47CC8C92D8686660 ON action (movement_action_type_id)');
        $this->addSql('CREATE INDEX IDX_47CC8C924BD2A4C0 ON action (report_id)');
        $this->addSql('CREATE TABLE action_movement (action_id INT NOT NULL, movement_id INT NOT NULL, PRIMARY KEY(action_id, movement_id))');
        $this->addSql('CREATE INDEX IDX_230AE5919D32F035 ON action_movement (action_id)');
        $this->addSql('CREATE INDEX IDX_230AE591229E70A7 ON action_movement (movement_id)');
        $this->addSql('CREATE TABLE action_type (id INT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE alert (id INT NOT NULL, action_id INT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_17FD46C19D32F035 ON alert (action_id)');
        $this->addSql('CREATE TABLE art_work (id INT NOT NULL, creation_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, total_length DOUBLE PRECISION DEFAULT NULL, total_width DOUBLE PRECISION DEFAULT NULL, total_height DOUBLE PRECISION DEFAULT NULL, registration_signature VARCHAR(255) DEFAULT NULL, descriptive_words VARCHAR(255) DEFAULT NULL, insurance_value INT DEFAULT NULL, insurance_value_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deposit_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, stop_number VARCHAR(255) DEFAULT NULL, other_registrations VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE art_work_log (id INT NOT NULL, user_id INT DEFAULT NULL, furniture_id INT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AC56464FA76ED395 ON art_work_log (user_id)');
        $this->addSql('CREATE INDEX IDX_AC56464FCF5485C3 ON art_work_log (furniture_id)');
        $this->addSql('CREATE TABLE attachment (id INT NOT NULL, furniture_id INT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, comment TEXT DEFAULT NULL, link VARCHAR(255) NOT NULL, principle_image BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_795FD9BBCF5485C3 ON attachment (furniture_id)');
        $this->addSql('CREATE TABLE author (id INT NOT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE author_type (id INT NOT NULL, author_id INT DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6831DFF6F675F31B ON author_type (author_id)');
        $this->addSql('CREATE TABLE building (id INT NOT NULL, site_id INT DEFAULT NULL, commune_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, distrib VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disappearance_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cedex VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E16F61D4F6BD1646 ON building (site_id)');
        $this->addSql('CREATE INDEX IDX_E16F61D4131A4F72 ON building (commune_id)');
        $this->addSql('CREATE TABLE commune (id INT NOT NULL, departement_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E2E2D1EECCF9E01E ON commune (departement_id)');
        $this->addSql('CREATE TABLE correspondent (id INT NOT NULL, establishment_id INT DEFAULT NULL, sub_division_id INT DEFAULT NULL, service_id INT DEFAULT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, phone VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E3D4D17F8565851 ON correspondent (establishment_id)');
        $this->addSql('CREATE INDEX IDX_E3D4D17FA47CE717 ON correspondent (sub_division_id)');
        $this->addSql('CREATE INDEX IDX_E3D4D17FED5CA9E6 ON correspondent (service_id)');
        $this->addSql('CREATE TABLE denomination (id INT NOT NULL, field_id INT DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_15AEA10C443707B0 ON denomination (field_id)');
        $this->addSql('CREATE TABLE denomination_material_technique (denomination_id INT NOT NULL, material_technique_id INT NOT NULL, PRIMARY KEY(denomination_id, material_technique_id))');
        $this->addSql('CREATE INDEX IDX_FAA0DF54E9293F06 ON denomination_material_technique (denomination_id)');
        $this->addSql('CREATE INDEX IDX_FAA0DF5411F25F26 ON denomination_material_technique (material_technique_id)');
        $this->addSql('CREATE TABLE departement (id INT NOT NULL, region_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disappearance_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C1765B6398260155 ON departement (region_id)');
        $this->addSql('CREATE TABLE deposit_status (id INT NOT NULL, depositor_id INT DEFAULT NULL, inventory_number VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6A8B385DEB8724B4 ON deposit_status (depositor_id)');
        $this->addSql('CREATE TABLE deposit_type (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE depositor (id INT NOT NULL, deposit_type_id INT DEFAULT NULL, acronym VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, dpt VARCHAR(255) DEFAULT NULL, distrib VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, contant VARCHAR(255) DEFAULT NULL, comment TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9D8D821FC48676C8 ON depositor (deposit_type_id)');
        $this->addSql('CREATE TABLE entry_mode (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE era (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE establishment (id INT NOT NULL, ministry_id INT DEFAULT NULL, type_id INT DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, acronym VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disappearance_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DBEFB1EEC7266135 ON establishment (ministry_id)');
        $this->addSql('CREATE INDEX IDX_DBEFB1EEC54C8C93 ON establishment (type_id)');
        $this->addSql('CREATE TABLE establishment_type (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE field (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE furniture (id INT NOT NULL, era_id INT DEFAULT NULL, type_id INT DEFAULT NULL, style_id INT DEFAULT NULL, material_technique_id INT DEFAULT NULL, denomination_id INT DEFAULT NULL, field_id INT DEFAULT NULL, status_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, length DOUBLE PRECISION DEFAULT NULL, width DOUBLE PRECISION DEFAULT NULL, height DOUBLE PRECISION DEFAULT NULL, depth DOUBLE PRECISION DEFAULT NULL, diameter DOUBLE PRECISION DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, number_of_unit INT DEFAULT NULL, description TEXT DEFAULT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_665DDAB3707300A1 ON furniture (era_id)');
        $this->addSql('CREATE INDEX IDX_665DDAB3C54C8C93 ON furniture (type_id)');
        $this->addSql('CREATE INDEX IDX_665DDAB3BACD6074 ON furniture (style_id)');
        $this->addSql('CREATE INDEX IDX_665DDAB311F25F26 ON furniture (material_technique_id)');
        $this->addSql('CREATE INDEX IDX_665DDAB3E9293F06 ON furniture (denomination_id)');
        $this->addSql('CREATE INDEX IDX_665DDAB3443707B0 ON furniture (field_id)');
        $this->addSql('CREATE INDEX IDX_665DDAB36BF700BD ON furniture (status_id)');
        $this->addSql('CREATE TABLE furniture_author (furniture_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY(furniture_id, author_id))');
        $this->addSql('CREATE INDEX IDX_386AF69ACF5485C3 ON furniture_author (furniture_id)');
        $this->addSql('CREATE INDEX IDX_386AF69AF675F31B ON furniture_author (author_id)');
        $this->addSql('CREATE TABLE location (id INT NOT NULL, establishment_id INT DEFAULT NULL, sub_division_id INT DEFAULT NULL, type_id INT DEFAULT NULL, room_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5E9E89CB8565851 ON location (establishment_id)');
        $this->addSql('CREATE INDEX IDX_5E9E89CBA47CE717 ON location (sub_division_id)');
        $this->addSql('CREATE INDEX IDX_5E9E89CBC54C8C93 ON location (type_id)');
        $this->addSql('CREATE INDEX IDX_5E9E89CB54177093 ON location (room_id)');
        $this->addSql('CREATE TABLE location_type (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE material_technique (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE ministry (id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, acronym VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disappearance_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE movement (id INT NOT NULL, location_id INT DEFAULT NULL, type_id INT DEFAULT NULL, furniture_id INT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, comment TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F4DD95F764D218E ON movement (location_id)');
        $this->addSql('CREATE INDEX IDX_F4DD95F7C54C8C93 ON movement (type_id)');
        $this->addSql('CREATE INDEX IDX_F4DD95F7CF5485C3 ON movement (furniture_id)');
        $this->addSql('CREATE TABLE movement_correspondent (movement_id INT NOT NULL, correspondent_id INT NOT NULL, PRIMARY KEY(movement_id, correspondent_id))');
        $this->addSql('CREATE INDEX IDX_B21E7704229E70A7 ON movement_correspondent (movement_id)');
        $this->addSql('CREATE INDEX IDX_B21E77042071082D ON movement_correspondent (correspondent_id)');
        $this->addSql('CREATE TABLE movement_action_type (id INT NOT NULL, movement_type_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5D22923BEA4ED04A ON movement_action_type (movement_type_id)');
        $this->addSql('CREATE TABLE movement_type (id INT NOT NULL, label TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE office_furniture (id INT NOT NULL, supplier VARCHAR(255) DEFAULT NULL, buying_price DOUBLE PRECISION DEFAULT NULL, state VARCHAR(255) DEFAULT NULL, unit_volume DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE property_status (id INT NOT NULL, entry_mode_id INT DEFAULT NULL, category_id INT DEFAULT NULL, entry_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, marking VARCHAR(255) DEFAULT NULL, property_percentage INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5770A605B032ADD ON property_status (entry_mode_id)');
        $this->addSql('CREATE INDEX IDX_5770A6012469DE2 ON property_status (category_id)');
        $this->addSql('CREATE TABLE property_status_category (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE region (id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disappearance_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE report (id INT NOT NULL, report_sub_type_id INT DEFAULT NULL, furniture_id INT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, comment TEXT DEFAULT NULL, collection_title BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C42F7784B8C7B6F ON report (report_sub_type_id)');
        $this->addSql('CREATE INDEX IDX_C42F7784CF5485C3 ON report (furniture_id)');
        $this->addSql('CREATE TABLE report_sub_type (id INT NOT NULL, report_type_id INT DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AB285195A5D5F193 ON report_sub_type (report_type_id)');
        $this->addSql('CREATE TABLE report_type (id INT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE responsible (id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE responsible_building (responsible_id INT NOT NULL, building_id INT NOT NULL, PRIMARY KEY(responsible_id, building_id))');
        $this->addSql('CREATE INDEX IDX_9FC4DEA3602AD315 ON responsible_building (responsible_id)');
        $this->addSql('CREATE INDEX IDX_9FC4DEA34D2A7E12 ON responsible_building (building_id)');
        $this->addSql('CREATE TABLE room (id INT NOT NULL, building_id INT DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, level VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_729F519B4D2A7E12 ON room (building_id)');
        $this->addSql('CREATE TABLE service (id INT NOT NULL, sub_division_id INT DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, acronym VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disappearance_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E19D9AD2A47CE717 ON service (sub_division_id)');
        $this->addSql('CREATE TABLE site (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disappearance_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE status (id INT NOT NULL, type VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, comment TEXT DEFAULT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE style (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE sub_division (id INT NOT NULL, establishment_id INT DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, acronym VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AAB8A94D8565851 ON sub_division (establishment_id)');
        $this->addSql('CREATE TABLE type (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "user" (id INT NOT NULL, ministry_id INT DEFAULT NULL, username VARCHAR(50) NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, password VARCHAR(100) DEFAULT NULL, roles TEXT DEFAULT NULL, comment TEXT DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE INDEX IDX_8D93D649C7266135 ON "user" (ministry_id)');
        $this->addSql('COMMENT ON COLUMN "user".roles IS \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE action ADD CONSTRAINT FK_47CC8C92C54C8C93 FOREIGN KEY (type_id) REFERENCES action_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE action ADD CONSTRAINT FK_47CC8C92D8686660 FOREIGN KEY (movement_action_type_id) REFERENCES movement_action_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE action ADD CONSTRAINT FK_47CC8C924BD2A4C0 FOREIGN KEY (report_id) REFERENCES report (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE action_movement ADD CONSTRAINT FK_230AE5919D32F035 FOREIGN KEY (action_id) REFERENCES action (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE action_movement ADD CONSTRAINT FK_230AE591229E70A7 FOREIGN KEY (movement_id) REFERENCES movement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C19D32F035 FOREIGN KEY (action_id) REFERENCES action (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE art_work ADD CONSTRAINT FK_5A6E1E1FBF396750 FOREIGN KEY (id) REFERENCES furniture (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE art_work_log ADD CONSTRAINT FK_AC56464FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE art_work_log ADD CONSTRAINT FK_AC56464FCF5485C3 FOREIGN KEY (furniture_id) REFERENCES furniture (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BBCF5485C3 FOREIGN KEY (furniture_id) REFERENCES furniture (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE author_type ADD CONSTRAINT FK_6831DFF6F675F31B FOREIGN KEY (author_id) REFERENCES author (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE building ADD CONSTRAINT FK_E16F61D4F6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE building ADD CONSTRAINT FK_E16F61D4131A4F72 FOREIGN KEY (commune_id) REFERENCES commune (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commune ADD CONSTRAINT FK_E2E2D1EECCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE correspondent ADD CONSTRAINT FK_E3D4D17F8565851 FOREIGN KEY (establishment_id) REFERENCES establishment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE correspondent ADD CONSTRAINT FK_E3D4D17FA47CE717 FOREIGN KEY (sub_division_id) REFERENCES sub_division (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE correspondent ADD CONSTRAINT FK_E3D4D17FED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE denomination ADD CONSTRAINT FK_15AEA10C443707B0 FOREIGN KEY (field_id) REFERENCES field (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE denomination_material_technique ADD CONSTRAINT FK_FAA0DF54E9293F06 FOREIGN KEY (denomination_id) REFERENCES denomination (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE denomination_material_technique ADD CONSTRAINT FK_FAA0DF5411F25F26 FOREIGN KEY (material_technique_id) REFERENCES material_technique (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE departement ADD CONSTRAINT FK_C1765B6398260155 FOREIGN KEY (region_id) REFERENCES region (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deposit_status ADD CONSTRAINT FK_6A8B385DEB8724B4 FOREIGN KEY (depositor_id) REFERENCES depositor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deposit_status ADD CONSTRAINT FK_6A8B385DBF396750 FOREIGN KEY (id) REFERENCES status (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE depositor ADD CONSTRAINT FK_9D8D821FC48676C8 FOREIGN KEY (deposit_type_id) REFERENCES deposit_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE establishment ADD CONSTRAINT FK_DBEFB1EEC7266135 FOREIGN KEY (ministry_id) REFERENCES ministry (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE establishment ADD CONSTRAINT FK_DBEFB1EEC54C8C93 FOREIGN KEY (type_id) REFERENCES establishment_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE furniture ADD CONSTRAINT FK_665DDAB3707300A1 FOREIGN KEY (era_id) REFERENCES era (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE furniture ADD CONSTRAINT FK_665DDAB3C54C8C93 FOREIGN KEY (type_id) REFERENCES type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE furniture ADD CONSTRAINT FK_665DDAB3BACD6074 FOREIGN KEY (style_id) REFERENCES style (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE furniture ADD CONSTRAINT FK_665DDAB311F25F26 FOREIGN KEY (material_technique_id) REFERENCES material_technique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE furniture ADD CONSTRAINT FK_665DDAB3E9293F06 FOREIGN KEY (denomination_id) REFERENCES denomination (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE furniture ADD CONSTRAINT FK_665DDAB3443707B0 FOREIGN KEY (field_id) REFERENCES field (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE furniture ADD CONSTRAINT FK_665DDAB36BF700BD FOREIGN KEY (status_id) REFERENCES status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE furniture_author ADD CONSTRAINT FK_386AF69ACF5485C3 FOREIGN KEY (furniture_id) REFERENCES furniture (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE furniture_author ADD CONSTRAINT FK_386AF69AF675F31B FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB8565851 FOREIGN KEY (establishment_id) REFERENCES establishment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CBA47CE717 FOREIGN KEY (sub_division_id) REFERENCES sub_division (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CBC54C8C93 FOREIGN KEY (type_id) REFERENCES location_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB54177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movement ADD CONSTRAINT FK_F4DD95F764D218E FOREIGN KEY (location_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movement ADD CONSTRAINT FK_F4DD95F7C54C8C93 FOREIGN KEY (type_id) REFERENCES movement_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movement ADD CONSTRAINT FK_F4DD95F7CF5485C3 FOREIGN KEY (furniture_id) REFERENCES furniture (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movement_correspondent ADD CONSTRAINT FK_B21E7704229E70A7 FOREIGN KEY (movement_id) REFERENCES movement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movement_correspondent ADD CONSTRAINT FK_B21E77042071082D FOREIGN KEY (correspondent_id) REFERENCES correspondent (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movement_action_type ADD CONSTRAINT FK_5D22923BEA4ED04A FOREIGN KEY (movement_type_id) REFERENCES movement_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE office_furniture ADD CONSTRAINT FK_70A9B38ABF396750 FOREIGN KEY (id) REFERENCES furniture (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE property_status ADD CONSTRAINT FK_5770A605B032ADD FOREIGN KEY (entry_mode_id) REFERENCES entry_mode (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE property_status ADD CONSTRAINT FK_5770A6012469DE2 FOREIGN KEY (category_id) REFERENCES property_status_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE property_status ADD CONSTRAINT FK_5770A60BF396750 FOREIGN KEY (id) REFERENCES status (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784B8C7B6F FOREIGN KEY (report_sub_type_id) REFERENCES report_sub_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784CF5485C3 FOREIGN KEY (furniture_id) REFERENCES furniture (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_sub_type ADD CONSTRAINT FK_AB285195A5D5F193 FOREIGN KEY (report_type_id) REFERENCES report_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE responsible_building ADD CONSTRAINT FK_9FC4DEA3602AD315 FOREIGN KEY (responsible_id) REFERENCES responsible (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE responsible_building ADD CONSTRAINT FK_9FC4DEA34D2A7E12 FOREIGN KEY (building_id) REFERENCES building (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519B4D2A7E12 FOREIGN KEY (building_id) REFERENCES building (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2A47CE717 FOREIGN KEY (sub_division_id) REFERENCES sub_division (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sub_division ADD CONSTRAINT FK_AAB8A94D8565851 FOREIGN KEY (establishment_id) REFERENCES establishment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649C7266135 FOREIGN KEY (ministry_id) REFERENCES ministry (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE action_movement DROP CONSTRAINT FK_230AE5919D32F035');
        $this->addSql('ALTER TABLE alert DROP CONSTRAINT FK_17FD46C19D32F035');
        $this->addSql('ALTER TABLE action DROP CONSTRAINT FK_47CC8C92C54C8C93');
        $this->addSql('ALTER TABLE author_type DROP CONSTRAINT FK_6831DFF6F675F31B');
        $this->addSql('ALTER TABLE furniture_author DROP CONSTRAINT FK_386AF69AF675F31B');
        $this->addSql('ALTER TABLE responsible_building DROP CONSTRAINT FK_9FC4DEA34D2A7E12');
        $this->addSql('ALTER TABLE room DROP CONSTRAINT FK_729F519B4D2A7E12');
        $this->addSql('ALTER TABLE building DROP CONSTRAINT FK_E16F61D4131A4F72');
        $this->addSql('ALTER TABLE movement_correspondent DROP CONSTRAINT FK_B21E77042071082D');
        $this->addSql('ALTER TABLE denomination_material_technique DROP CONSTRAINT FK_FAA0DF54E9293F06');
        $this->addSql('ALTER TABLE furniture DROP CONSTRAINT FK_665DDAB3E9293F06');
        $this->addSql('ALTER TABLE commune DROP CONSTRAINT FK_E2E2D1EECCF9E01E');
        $this->addSql('ALTER TABLE depositor DROP CONSTRAINT FK_9D8D821FC48676C8');
        $this->addSql('ALTER TABLE deposit_status DROP CONSTRAINT FK_6A8B385DEB8724B4');
        $this->addSql('ALTER TABLE property_status DROP CONSTRAINT FK_5770A605B032ADD');
        $this->addSql('ALTER TABLE furniture DROP CONSTRAINT FK_665DDAB3707300A1');
        $this->addSql('ALTER TABLE correspondent DROP CONSTRAINT FK_E3D4D17F8565851');
        $this->addSql('ALTER TABLE location DROP CONSTRAINT FK_5E9E89CB8565851');
        $this->addSql('ALTER TABLE sub_division DROP CONSTRAINT FK_AAB8A94D8565851');
        $this->addSql('ALTER TABLE establishment DROP CONSTRAINT FK_DBEFB1EEC54C8C93');
        $this->addSql('ALTER TABLE denomination DROP CONSTRAINT FK_15AEA10C443707B0');
        $this->addSql('ALTER TABLE furniture DROP CONSTRAINT FK_665DDAB3443707B0');
        $this->addSql('ALTER TABLE art_work DROP CONSTRAINT FK_5A6E1E1FBF396750');
        $this->addSql('ALTER TABLE art_work_log DROP CONSTRAINT FK_AC56464FCF5485C3');
        $this->addSql('ALTER TABLE attachment DROP CONSTRAINT FK_795FD9BBCF5485C3');
        $this->addSql('ALTER TABLE furniture_author DROP CONSTRAINT FK_386AF69ACF5485C3');
        $this->addSql('ALTER TABLE movement DROP CONSTRAINT FK_F4DD95F7CF5485C3');
        $this->addSql('ALTER TABLE office_furniture DROP CONSTRAINT FK_70A9B38ABF396750');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784CF5485C3');
        $this->addSql('ALTER TABLE movement DROP CONSTRAINT FK_F4DD95F764D218E');
        $this->addSql('ALTER TABLE location DROP CONSTRAINT FK_5E9E89CBC54C8C93');
        $this->addSql('ALTER TABLE denomination_material_technique DROP CONSTRAINT FK_FAA0DF5411F25F26');
        $this->addSql('ALTER TABLE furniture DROP CONSTRAINT FK_665DDAB311F25F26');
        $this->addSql('ALTER TABLE establishment DROP CONSTRAINT FK_DBEFB1EEC7266135');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649C7266135');
        $this->addSql('ALTER TABLE action_movement DROP CONSTRAINT FK_230AE591229E70A7');
        $this->addSql('ALTER TABLE movement_correspondent DROP CONSTRAINT FK_B21E7704229E70A7');
        $this->addSql('ALTER TABLE action DROP CONSTRAINT FK_47CC8C92D8686660');
        $this->addSql('ALTER TABLE movement DROP CONSTRAINT FK_F4DD95F7C54C8C93');
        $this->addSql('ALTER TABLE movement_action_type DROP CONSTRAINT FK_5D22923BEA4ED04A');
        $this->addSql('ALTER TABLE property_status DROP CONSTRAINT FK_5770A6012469DE2');
        $this->addSql('ALTER TABLE departement DROP CONSTRAINT FK_C1765B6398260155');
        $this->addSql('ALTER TABLE action DROP CONSTRAINT FK_47CC8C924BD2A4C0');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784B8C7B6F');
        $this->addSql('ALTER TABLE report_sub_type DROP CONSTRAINT FK_AB285195A5D5F193');
        $this->addSql('ALTER TABLE responsible_building DROP CONSTRAINT FK_9FC4DEA3602AD315');
        $this->addSql('ALTER TABLE location DROP CONSTRAINT FK_5E9E89CB54177093');
        $this->addSql('ALTER TABLE correspondent DROP CONSTRAINT FK_E3D4D17FED5CA9E6');
        $this->addSql('ALTER TABLE building DROP CONSTRAINT FK_E16F61D4F6BD1646');
        $this->addSql('ALTER TABLE deposit_status DROP CONSTRAINT FK_6A8B385DBF396750');
        $this->addSql('ALTER TABLE furniture DROP CONSTRAINT FK_665DDAB36BF700BD');
        $this->addSql('ALTER TABLE property_status DROP CONSTRAINT FK_5770A60BF396750');
        $this->addSql('ALTER TABLE furniture DROP CONSTRAINT FK_665DDAB3BACD6074');
        $this->addSql('ALTER TABLE correspondent DROP CONSTRAINT FK_E3D4D17FA47CE717');
        $this->addSql('ALTER TABLE location DROP CONSTRAINT FK_5E9E89CBA47CE717');
        $this->addSql('ALTER TABLE service DROP CONSTRAINT FK_E19D9AD2A47CE717');
        $this->addSql('ALTER TABLE furniture DROP CONSTRAINT FK_665DDAB3C54C8C93');
        $this->addSql('ALTER TABLE art_work_log DROP CONSTRAINT FK_AC56464FA76ED395');
        $this->addSql('DROP SEQUENCE action_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE action_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE alert_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE art_work_log_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE attachment_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE author_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE author_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE building_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE commune_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE correspondent_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE denomination_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE departement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE deposit_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE depositor_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE entry_mode_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE era_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE establishment_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE establishment_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE field_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE furniture_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE location_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE location_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material_technique_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ministry_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE movement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE movement_action_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE movement_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE property_status_category_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE region_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE report_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE report_sub_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE report_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE responsible_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE room_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE service_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE site_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE style_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE sub_division_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE user_id_seq CASCADE');
        $this->addSql('DROP TABLE action');
        $this->addSql('DROP TABLE action_movement');
        $this->addSql('DROP TABLE action_type');
        $this->addSql('DROP TABLE alert');
        $this->addSql('DROP TABLE art_work');
        $this->addSql('DROP TABLE art_work_log');
        $this->addSql('DROP TABLE attachment');
        $this->addSql('DROP TABLE author');
        $this->addSql('DROP TABLE author_type');
        $this->addSql('DROP TABLE building');
        $this->addSql('DROP TABLE commune');
        $this->addSql('DROP TABLE correspondent');
        $this->addSql('DROP TABLE denomination');
        $this->addSql('DROP TABLE denomination_material_technique');
        $this->addSql('DROP TABLE departement');
        $this->addSql('DROP TABLE deposit_status');
        $this->addSql('DROP TABLE deposit_type');
        $this->addSql('DROP TABLE depositor');
        $this->addSql('DROP TABLE entry_mode');
        $this->addSql('DROP TABLE era');
        $this->addSql('DROP TABLE establishment');
        $this->addSql('DROP TABLE establishment_type');
        $this->addSql('DROP TABLE field');
        $this->addSql('DROP TABLE furniture');
        $this->addSql('DROP TABLE furniture_author');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE location_type');
        $this->addSql('DROP TABLE material_technique');
        $this->addSql('DROP TABLE ministry');
        $this->addSql('DROP TABLE movement');
        $this->addSql('DROP TABLE movement_correspondent');
        $this->addSql('DROP TABLE movement_action_type');
        $this->addSql('DROP TABLE movement_type');
        $this->addSql('DROP TABLE office_furniture');
        $this->addSql('DROP TABLE property_status');
        $this->addSql('DROP TABLE property_status_category');
        $this->addSql('DROP TABLE region');
        $this->addSql('DROP TABLE report');
        $this->addSql('DROP TABLE report_sub_type');
        $this->addSql('DROP TABLE report_type');
        $this->addSql('DROP TABLE responsible');
        $this->addSql('DROP TABLE responsible_building');
        $this->addSql('DROP TABLE room');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE site');
        $this->addSql('DROP TABLE status');
        $this->addSql('DROP TABLE style');
        $this->addSql('DROP TABLE sub_division');
        $this->addSql('DROP TABLE type');
        $this->addSql('DROP TABLE "user"');
    }
}
