<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210324083152 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE Action_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ActionType_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Alert_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ArtWorkLog_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Attachment_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Author_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE AuthorType_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Building_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Commune_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Correspondent_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Denomination_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Departement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE DepositType_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Depositor_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE EntryMode_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Era_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Establishment_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE EstablishmentType_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Furniture_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Location_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE LocationType_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE MaterialTechnique_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Ministry_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Movement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE MovementActionType_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE MovementType_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE PropertyStatusCategory_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Region_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Report_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ReportSubType_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ReportType_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Responsible_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Room_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Service_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Site_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Style_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE SubDivision_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE Type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE User_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE domaine_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE Action (id INT NOT NULL, type_id INT DEFAULT NULL, report_id INT DEFAULT NULL, comment TEXT DEFAULT NULL, startDate TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, endDate TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, period INT NOT NULL, actionNature VARCHAR(255) DEFAULT NULL, movementActionType_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_406089A4C54C8C93 ON Action (type_id)');
        $this->addSql('CREATE INDEX IDX_406089A4CC710B8A ON Action (movementActionType_id)');
        $this->addSql('CREATE INDEX IDX_406089A44BD2A4C0 ON Action (report_id)');
        $this->addSql('CREATE TABLE action_movement (action_id INT NOT NULL, movement_id INT NOT NULL, PRIMARY KEY(action_id, movement_id))');
        $this->addSql('CREATE INDEX IDX_230AE5919D32F035 ON action_movement (action_id)');
        $this->addSql('CREATE INDEX IDX_230AE591229E70A7 ON action_movement (movement_id)');
        $this->addSql('CREATE TABLE ActionType (id INT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Alert (id INT NOT NULL, action_id INT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D63C69C59D32F035 ON Alert (action_id)');
        $this->addSql('CREATE TABLE ArtWork (id INT NOT NULL, creationDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, totalLength DOUBLE PRECISION DEFAULT NULL, totalWidth DOUBLE PRECISION DEFAULT NULL, totalHeight DOUBLE PRECISION DEFAULT NULL, registrationSignature VARCHAR(255) DEFAULT NULL, descriptiveWords VARCHAR(255) DEFAULT NULL, insuranceValue INT DEFAULT NULL, insuranceValueDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, depositDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, stopNumber VARCHAR(255) DEFAULT NULL, otherRegistrations VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE ArtWorkLog (id INT NOT NULL, user_id INT DEFAULT NULL, furniture_id INT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5C6B2EFDA76ED395 ON ArtWorkLog (user_id)');
        $this->addSql('CREATE INDEX IDX_5C6B2EFDCF5485C3 ON ArtWorkLog (furniture_id)');
        $this->addSql('CREATE TABLE Attachment (id INT NOT NULL, furniture_id INT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, comment TEXT DEFAULT NULL, link VARCHAR(255) NOT NULL, principleImage BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3602DA6BCF5485C3 ON Attachment (furniture_id)');
        $this->addSql('CREATE TABLE Author (id INT NOT NULL, firstName VARCHAR(255) DEFAULT NULL, lastName VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE AuthorType (id INT NOT NULL, author_id INT DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CF9D36B1F675F31B ON AuthorType (author_id)');
        $this->addSql('CREATE TABLE Building (id INT NOT NULL, site_id INT DEFAULT NULL, commune_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, distrib VARCHAR(255) DEFAULT NULL, startDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disappearanceDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cedex VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_18190382F6BD1646 ON Building (site_id)');
        $this->addSql('CREATE INDEX IDX_18190382131A4F72 ON Building (commune_id)');
        $this->addSql('CREATE TABLE Commune (id INT NOT NULL, departement_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2D5FE872CCF9E01E ON Commune (departement_id)');
        $this->addSql('CREATE TABLE Correspondent (id INT NOT NULL, establishment_id INT DEFAULT NULL, service_id INT DEFAULT NULL, firstName VARCHAR(255) DEFAULT NULL, lastName VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, startDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, endDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, subDivision_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_50AA9A8A8565851 ON Correspondent (establishment_id)');
        $this->addSql('CREATE INDEX IDX_50AA9A8A88997EEB ON Correspondent (subDivision_id)');
        $this->addSql('CREATE INDEX IDX_50AA9A8AED5CA9E6 ON Correspondent (service_id)');
        $this->addSql('CREATE TABLE Denomination (id INT NOT NULL, domaine_id INT DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D9F7AF44272FC9F ON Denomination (domaine_id)');
        $this->addSql('CREATE TABLE denomination_materialtechnique (denomination_id INT NOT NULL, materialtechnique_id INT NOT NULL, PRIMARY KEY(denomination_id, materialtechnique_id))');
        $this->addSql('CREATE INDEX IDX_605345DEE9293F06 ON denomination_materialtechnique (denomination_id)');
        $this->addSql('CREATE INDEX IDX_605345DEE22B4BD0 ON denomination_materialtechnique (materialtechnique_id)');
        $this->addSql('CREATE TABLE Departement (id INT NOT NULL, region_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, startDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disappearanceDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_47EAD4B498260155 ON Departement (region_id)');
        $this->addSql('CREATE TABLE DepositStatus (id INT NOT NULL, depositor_id INT DEFAULT NULL, inventoryNumber VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CFBCDA98EB8724B4 ON DepositStatus (depositor_id)');
        $this->addSql('CREATE TABLE DepositType (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Depositor (id INT NOT NULL, acronym VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, dpt VARCHAR(255) DEFAULT NULL, distrib VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, startDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, endDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, contant VARCHAR(255) DEFAULT NULL, comment TEXT DEFAULT NULL, depositType_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1F7C00BCE2490FCD ON Depositor (depositType_id)');
        $this->addSql('CREATE TABLE EntryMode (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Era (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Establishment (id INT NOT NULL, ministry_id INT DEFAULT NULL, type_id INT DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, acronym VARCHAR(255) DEFAULT NULL, startDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disappearanceDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6891FA1BC7266135 ON Establishment (ministry_id)');
        $this->addSql('CREATE INDEX IDX_6891FA1BC54C8C93 ON Establishment (type_id)');
        $this->addSql('CREATE TABLE EstablishmentType (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Furniture (id INT NOT NULL, era_id INT DEFAULT NULL, type_id INT DEFAULT NULL, style_id INT DEFAULT NULL, denomination_id INT DEFAULT NULL, field_id INT DEFAULT NULL, status_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, length DOUBLE PRECISION DEFAULT NULL, width DOUBLE PRECISION DEFAULT NULL, height DOUBLE PRECISION DEFAULT NULL, depth DOUBLE PRECISION DEFAULT NULL, diameter DOUBLE PRECISION DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, numberOfUnit INT DEFAULT NULL, description TEXT DEFAULT NULL, materialTechnique_id INT DEFAULT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E4AC5810707300A1 ON Furniture (era_id)');
        $this->addSql('CREATE INDEX IDX_E4AC5810C54C8C93 ON Furniture (type_id)');
        $this->addSql('CREATE INDEX IDX_E4AC5810BACD6074 ON Furniture (style_id)');
        $this->addSql('CREATE INDEX IDX_E4AC5810FA1A9028 ON Furniture (materialTechnique_id)');
        $this->addSql('CREATE INDEX IDX_E4AC5810E9293F06 ON Furniture (denomination_id)');
        $this->addSql('CREATE INDEX IDX_E4AC5810443707B0 ON Furniture (field_id)');
        $this->addSql('CREATE INDEX IDX_E4AC58106BF700BD ON Furniture (status_id)');
        $this->addSql('CREATE TABLE furniture_author (furniture_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY(furniture_id, author_id))');
        $this->addSql('CREATE INDEX IDX_386AF69ACF5485C3 ON furniture_author (furniture_id)');
        $this->addSql('CREATE INDEX IDX_386AF69AF675F31B ON furniture_author (author_id)');
        $this->addSql('CREATE TABLE Location (id INT NOT NULL, establishment_id INT DEFAULT NULL, type_id INT DEFAULT NULL, room_id INT DEFAULT NULL, subDivision_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A7E8EB9D8565851 ON Location (establishment_id)');
        $this->addSql('CREATE INDEX IDX_A7E8EB9D88997EEB ON Location (subDivision_id)');
        $this->addSql('CREATE INDEX IDX_A7E8EB9DC54C8C93 ON Location (type_id)');
        $this->addSql('CREATE INDEX IDX_A7E8EB9D54177093 ON Location (room_id)');
        $this->addSql('CREATE TABLE LocationType (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE MaterialTechnique (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Ministry (id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, acronym VARCHAR(255) DEFAULT NULL, startDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disappearanceDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Movement (id INT NOT NULL, location_id INT DEFAULT NULL, type_id INT DEFAULT NULL, furniture_id INT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, comment TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DABF7A164D218E ON Movement (location_id)');
        $this->addSql('CREATE INDEX IDX_DABF7A1C54C8C93 ON Movement (type_id)');
        $this->addSql('CREATE INDEX IDX_DABF7A1CF5485C3 ON Movement (furniture_id)');
        $this->addSql('CREATE TABLE movement_correspondent (movement_id INT NOT NULL, correspondent_id INT NOT NULL, PRIMARY KEY(movement_id, correspondent_id))');
        $this->addSql('CREATE INDEX IDX_B21E7704229E70A7 ON movement_correspondent (movement_id)');
        $this->addSql('CREATE INDEX IDX_B21E77042071082D ON movement_correspondent (correspondent_id)');
        $this->addSql('CREATE TABLE MovementActionType (id INT NOT NULL, label VARCHAR(255) NOT NULL, movementType_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_31DD29DB9EE20CB0 ON MovementActionType (movementType_id)');
        $this->addSql('CREATE TABLE MovementType (id INT NOT NULL, label TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE OfficeFurniture (id INT NOT NULL, supplier VARCHAR(255) DEFAULT NULL, buyingPrice DOUBLE PRECISION DEFAULT NULL, state VARCHAR(255) DEFAULT NULL, unitVolume DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE PropertyStatus (id INT NOT NULL, category_id INT DEFAULT NULL, entryDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, marking VARCHAR(255) DEFAULT NULL, propertyPercentage INT DEFAULT NULL, entryMode_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FDE335637E5A47EB ON PropertyStatus (entryMode_id)');
        $this->addSql('CREATE INDEX IDX_FDE3356312469DE2 ON PropertyStatus (category_id)');
        $this->addSql('CREATE TABLE PropertyStatusCategory (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Region (id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, startDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disappearanceDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Report (id INT NOT NULL, furniture_id INT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, comment TEXT DEFAULT NULL, collectionTitle BOOLEAN DEFAULT NULL, reportSubType_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C38372B26DE6D215 ON Report (reportSubType_id)');
        $this->addSql('CREATE INDEX IDX_C38372B2CF5485C3 ON Report (furniture_id)');
        $this->addSql('CREATE TABLE ReportSubType (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, reportType_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_595ACAE9DA318713 ON ReportSubType (reportType_id)');
        $this->addSql('CREATE TABLE ReportType (id INT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Responsible (id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, firstName VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, startDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, endDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE responsible_building (responsible_id INT NOT NULL, building_id INT NOT NULL, PRIMARY KEY(responsible_id, building_id))');
        $this->addSql('CREATE INDEX IDX_9FC4DEA3602AD315 ON responsible_building (responsible_id)');
        $this->addSql('CREATE INDEX IDX_9FC4DEA34D2A7E12 ON responsible_building (building_id)');
        $this->addSql('CREATE TABLE Room (id INT NOT NULL, building_id INT DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, level VARCHAR(255) DEFAULT NULL, startDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, endDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D2ADFEA54D2A7E12 ON Room (building_id)');
        $this->addSql('CREATE TABLE Service (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, acronym VARCHAR(255) DEFAULT NULL, startDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disappearanceDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, subDivision_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2E20A34E88997EEB ON Service (subDivision_id)');
        $this->addSql('CREATE TABLE Site (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, startDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disappearanceDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Status (id INT NOT NULL, type VARCHAR(255) DEFAULT NULL, startDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, endDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, comment TEXT DEFAULT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Style (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE SubDivision (id INT NOT NULL, establishment_id INT DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, acronym VARCHAR(255) DEFAULT NULL, startDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, endDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_646D171C8565851 ON SubDivision (establishment_id)');
        $this->addSql('CREATE TABLE Type (id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "User" (id INT NOT NULL, ministry_id INT DEFAULT NULL, username VARCHAR(50) NOT NULL, firstName VARCHAR(50) NOT NULL, lastName VARCHAR(50) NOT NULL, password VARCHAR(100) DEFAULT NULL, roles TEXT DEFAULT NULL, comment TEXT DEFAULT NULL, startDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, endDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DA17977F85E0677 ON "User" (username)');
        $this->addSql('CREATE INDEX IDX_2DA17977C7266135 ON "User" (ministry_id)');
        $this->addSql('COMMENT ON COLUMN "User".roles IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE domaine (id INT NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE Action ADD CONSTRAINT FK_406089A4C54C8C93 FOREIGN KEY (type_id) REFERENCES ActionType (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Action ADD CONSTRAINT FK_406089A4CC710B8A FOREIGN KEY (movementActionType_id) REFERENCES MovementActionType (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Action ADD CONSTRAINT FK_406089A44BD2A4C0 FOREIGN KEY (report_id) REFERENCES Report (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE action_movement ADD CONSTRAINT FK_230AE5919D32F035 FOREIGN KEY (action_id) REFERENCES Action (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE action_movement ADD CONSTRAINT FK_230AE591229E70A7 FOREIGN KEY (movement_id) REFERENCES Movement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Alert ADD CONSTRAINT FK_D63C69C59D32F035 FOREIGN KEY (action_id) REFERENCES Action (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ArtWork ADD CONSTRAINT FK_E79053D4BF396750 FOREIGN KEY (id) REFERENCES Furniture (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ArtWorkLog ADD CONSTRAINT FK_5C6B2EFDA76ED395 FOREIGN KEY (user_id) REFERENCES "User" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ArtWorkLog ADD CONSTRAINT FK_5C6B2EFDCF5485C3 FOREIGN KEY (furniture_id) REFERENCES Furniture (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Attachment ADD CONSTRAINT FK_3602DA6BCF5485C3 FOREIGN KEY (furniture_id) REFERENCES Furniture (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE AuthorType ADD CONSTRAINT FK_CF9D36B1F675F31B FOREIGN KEY (author_id) REFERENCES Author (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Building ADD CONSTRAINT FK_18190382F6BD1646 FOREIGN KEY (site_id) REFERENCES Site (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Building ADD CONSTRAINT FK_18190382131A4F72 FOREIGN KEY (commune_id) REFERENCES Commune (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Commune ADD CONSTRAINT FK_2D5FE872CCF9E01E FOREIGN KEY (departement_id) REFERENCES Departement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Correspondent ADD CONSTRAINT FK_50AA9A8A8565851 FOREIGN KEY (establishment_id) REFERENCES Establishment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Correspondent ADD CONSTRAINT FK_50AA9A8A88997EEB FOREIGN KEY (subDivision_id) REFERENCES SubDivision (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Correspondent ADD CONSTRAINT FK_50AA9A8AED5CA9E6 FOREIGN KEY (service_id) REFERENCES Service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Denomination ADD CONSTRAINT FK_D9F7AF44272FC9F FOREIGN KEY (domaine_id) REFERENCES domaine (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE denomination_materialtechnique ADD CONSTRAINT FK_605345DEE9293F06 FOREIGN KEY (denomination_id) REFERENCES Denomination (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE denomination_materialtechnique ADD CONSTRAINT FK_605345DEE22B4BD0 FOREIGN KEY (materialtechnique_id) REFERENCES MaterialTechnique (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Departement ADD CONSTRAINT FK_47EAD4B498260155 FOREIGN KEY (region_id) REFERENCES Region (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE DepositStatus ADD CONSTRAINT FK_CFBCDA98EB8724B4 FOREIGN KEY (depositor_id) REFERENCES Depositor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE DepositStatus ADD CONSTRAINT FK_CFBCDA98BF396750 FOREIGN KEY (id) REFERENCES Status (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Depositor ADD CONSTRAINT FK_1F7C00BCE2490FCD FOREIGN KEY (depositType_id) REFERENCES DepositType (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Establishment ADD CONSTRAINT FK_6891FA1BC7266135 FOREIGN KEY (ministry_id) REFERENCES Ministry (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Establishment ADD CONSTRAINT FK_6891FA1BC54C8C93 FOREIGN KEY (type_id) REFERENCES EstablishmentType (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Furniture ADD CONSTRAINT FK_E4AC5810707300A1 FOREIGN KEY (era_id) REFERENCES Era (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Furniture ADD CONSTRAINT FK_E4AC5810C54C8C93 FOREIGN KEY (type_id) REFERENCES Type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Furniture ADD CONSTRAINT FK_E4AC5810BACD6074 FOREIGN KEY (style_id) REFERENCES Style (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Furniture ADD CONSTRAINT FK_E4AC5810FA1A9028 FOREIGN KEY (materialTechnique_id) REFERENCES MaterialTechnique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Furniture ADD CONSTRAINT FK_E4AC5810E9293F06 FOREIGN KEY (denomination_id) REFERENCES Denomination (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Furniture ADD CONSTRAINT FK_E4AC5810443707B0 FOREIGN KEY (field_id) REFERENCES domaine (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Furniture ADD CONSTRAINT FK_E4AC58106BF700BD FOREIGN KEY (status_id) REFERENCES Status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE furniture_author ADD CONSTRAINT FK_386AF69ACF5485C3 FOREIGN KEY (furniture_id) REFERENCES Furniture (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE furniture_author ADD CONSTRAINT FK_386AF69AF675F31B FOREIGN KEY (author_id) REFERENCES Author (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Location ADD CONSTRAINT FK_A7E8EB9D8565851 FOREIGN KEY (establishment_id) REFERENCES Establishment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Location ADD CONSTRAINT FK_A7E8EB9D88997EEB FOREIGN KEY (subDivision_id) REFERENCES SubDivision (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Location ADD CONSTRAINT FK_A7E8EB9DC54C8C93 FOREIGN KEY (type_id) REFERENCES LocationType (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Location ADD CONSTRAINT FK_A7E8EB9D54177093 FOREIGN KEY (room_id) REFERENCES Room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Movement ADD CONSTRAINT FK_DABF7A164D218E FOREIGN KEY (location_id) REFERENCES Location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Movement ADD CONSTRAINT FK_DABF7A1C54C8C93 FOREIGN KEY (type_id) REFERENCES MovementType (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Movement ADD CONSTRAINT FK_DABF7A1CF5485C3 FOREIGN KEY (furniture_id) REFERENCES Furniture (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movement_correspondent ADD CONSTRAINT FK_B21E7704229E70A7 FOREIGN KEY (movement_id) REFERENCES Movement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movement_correspondent ADD CONSTRAINT FK_B21E77042071082D FOREIGN KEY (correspondent_id) REFERENCES Correspondent (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE MovementActionType ADD CONSTRAINT FK_31DD29DB9EE20CB0 FOREIGN KEY (movementType_id) REFERENCES MovementType (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE OfficeFurniture ADD CONSTRAINT FK_DA0F5F31BF396750 FOREIGN KEY (id) REFERENCES Furniture (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE PropertyStatus ADD CONSTRAINT FK_FDE335637E5A47EB FOREIGN KEY (entryMode_id) REFERENCES EntryMode (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE PropertyStatus ADD CONSTRAINT FK_FDE3356312469DE2 FOREIGN KEY (category_id) REFERENCES PropertyStatusCategory (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE PropertyStatus ADD CONSTRAINT FK_FDE33563BF396750 FOREIGN KEY (id) REFERENCES Status (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Report ADD CONSTRAINT FK_C38372B26DE6D215 FOREIGN KEY (reportSubType_id) REFERENCES ReportSubType (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Report ADD CONSTRAINT FK_C38372B2CF5485C3 FOREIGN KEY (furniture_id) REFERENCES Furniture (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ReportSubType ADD CONSTRAINT FK_595ACAE9DA318713 FOREIGN KEY (reportType_id) REFERENCES ReportType (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE responsible_building ADD CONSTRAINT FK_9FC4DEA3602AD315 FOREIGN KEY (responsible_id) REFERENCES Responsible (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE responsible_building ADD CONSTRAINT FK_9FC4DEA34D2A7E12 FOREIGN KEY (building_id) REFERENCES Building (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Room ADD CONSTRAINT FK_D2ADFEA54D2A7E12 FOREIGN KEY (building_id) REFERENCES Building (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Service ADD CONSTRAINT FK_2E20A34E88997EEB FOREIGN KEY (subDivision_id) REFERENCES SubDivision (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE SubDivision ADD CONSTRAINT FK_646D171C8565851 FOREIGN KEY (establishment_id) REFERENCES Establishment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "User" ADD CONSTRAINT FK_2DA17977C7266135 FOREIGN KEY (ministry_id) REFERENCES Ministry (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE action_movement DROP CONSTRAINT FK_230AE5919D32F035');
        $this->addSql('ALTER TABLE Alert DROP CONSTRAINT FK_D63C69C59D32F035');
        $this->addSql('ALTER TABLE Action DROP CONSTRAINT FK_406089A4C54C8C93');
        $this->addSql('ALTER TABLE AuthorType DROP CONSTRAINT FK_CF9D36B1F675F31B');
        $this->addSql('ALTER TABLE furniture_author DROP CONSTRAINT FK_386AF69AF675F31B');
        $this->addSql('ALTER TABLE responsible_building DROP CONSTRAINT FK_9FC4DEA34D2A7E12');
        $this->addSql('ALTER TABLE Room DROP CONSTRAINT FK_D2ADFEA54D2A7E12');
        $this->addSql('ALTER TABLE Building DROP CONSTRAINT FK_18190382131A4F72');
        $this->addSql('ALTER TABLE movement_correspondent DROP CONSTRAINT FK_B21E77042071082D');
        $this->addSql('ALTER TABLE denomination_materialtechnique DROP CONSTRAINT FK_605345DEE9293F06');
        $this->addSql('ALTER TABLE Furniture DROP CONSTRAINT FK_E4AC5810E9293F06');
        $this->addSql('ALTER TABLE Commune DROP CONSTRAINT FK_2D5FE872CCF9E01E');
        $this->addSql('ALTER TABLE Depositor DROP CONSTRAINT FK_1F7C00BCE2490FCD');
        $this->addSql('ALTER TABLE DepositStatus DROP CONSTRAINT FK_CFBCDA98EB8724B4');
        $this->addSql('ALTER TABLE PropertyStatus DROP CONSTRAINT FK_FDE335637E5A47EB');
        $this->addSql('ALTER TABLE Furniture DROP CONSTRAINT FK_E4AC5810707300A1');
        $this->addSql('ALTER TABLE Correspondent DROP CONSTRAINT FK_50AA9A8A8565851');
        $this->addSql('ALTER TABLE Location DROP CONSTRAINT FK_A7E8EB9D8565851');
        $this->addSql('ALTER TABLE SubDivision DROP CONSTRAINT FK_646D171C8565851');
        $this->addSql('ALTER TABLE Establishment DROP CONSTRAINT FK_6891FA1BC54C8C93');
        $this->addSql('ALTER TABLE ArtWork DROP CONSTRAINT FK_E79053D4BF396750');
        $this->addSql('ALTER TABLE ArtWorkLog DROP CONSTRAINT FK_5C6B2EFDCF5485C3');
        $this->addSql('ALTER TABLE Attachment DROP CONSTRAINT FK_3602DA6BCF5485C3');
        $this->addSql('ALTER TABLE furniture_author DROP CONSTRAINT FK_386AF69ACF5485C3');
        $this->addSql('ALTER TABLE Movement DROP CONSTRAINT FK_DABF7A1CF5485C3');
        $this->addSql('ALTER TABLE OfficeFurniture DROP CONSTRAINT FK_DA0F5F31BF396750');
        $this->addSql('ALTER TABLE Report DROP CONSTRAINT FK_C38372B2CF5485C3');
        $this->addSql('ALTER TABLE Movement DROP CONSTRAINT FK_DABF7A164D218E');
        $this->addSql('ALTER TABLE Location DROP CONSTRAINT FK_A7E8EB9DC54C8C93');
        $this->addSql('ALTER TABLE denomination_materialtechnique DROP CONSTRAINT FK_605345DEE22B4BD0');
        $this->addSql('ALTER TABLE Furniture DROP CONSTRAINT FK_E4AC5810FA1A9028');
        $this->addSql('ALTER TABLE Establishment DROP CONSTRAINT FK_6891FA1BC7266135');
        $this->addSql('ALTER TABLE "User" DROP CONSTRAINT FK_2DA17977C7266135');
        $this->addSql('ALTER TABLE action_movement DROP CONSTRAINT FK_230AE591229E70A7');
        $this->addSql('ALTER TABLE movement_correspondent DROP CONSTRAINT FK_B21E7704229E70A7');
        $this->addSql('ALTER TABLE Action DROP CONSTRAINT FK_406089A4CC710B8A');
        $this->addSql('ALTER TABLE Movement DROP CONSTRAINT FK_DABF7A1C54C8C93');
        $this->addSql('ALTER TABLE MovementActionType DROP CONSTRAINT FK_31DD29DB9EE20CB0');
        $this->addSql('ALTER TABLE PropertyStatus DROP CONSTRAINT FK_FDE3356312469DE2');
        $this->addSql('ALTER TABLE Departement DROP CONSTRAINT FK_47EAD4B498260155');
        $this->addSql('ALTER TABLE Action DROP CONSTRAINT FK_406089A44BD2A4C0');
        $this->addSql('ALTER TABLE Report DROP CONSTRAINT FK_C38372B26DE6D215');
        $this->addSql('ALTER TABLE ReportSubType DROP CONSTRAINT FK_595ACAE9DA318713');
        $this->addSql('ALTER TABLE responsible_building DROP CONSTRAINT FK_9FC4DEA3602AD315');
        $this->addSql('ALTER TABLE Location DROP CONSTRAINT FK_A7E8EB9D54177093');
        $this->addSql('ALTER TABLE Correspondent DROP CONSTRAINT FK_50AA9A8AED5CA9E6');
        $this->addSql('ALTER TABLE Building DROP CONSTRAINT FK_18190382F6BD1646');
        $this->addSql('ALTER TABLE DepositStatus DROP CONSTRAINT FK_CFBCDA98BF396750');
        $this->addSql('ALTER TABLE Furniture DROP CONSTRAINT FK_E4AC58106BF700BD');
        $this->addSql('ALTER TABLE PropertyStatus DROP CONSTRAINT FK_FDE33563BF396750');
        $this->addSql('ALTER TABLE Furniture DROP CONSTRAINT FK_E4AC5810BACD6074');
        $this->addSql('ALTER TABLE Correspondent DROP CONSTRAINT FK_50AA9A8A88997EEB');
        $this->addSql('ALTER TABLE Location DROP CONSTRAINT FK_A7E8EB9D88997EEB');
        $this->addSql('ALTER TABLE Service DROP CONSTRAINT FK_2E20A34E88997EEB');
        $this->addSql('ALTER TABLE Furniture DROP CONSTRAINT FK_E4AC5810C54C8C93');
        $this->addSql('ALTER TABLE ArtWorkLog DROP CONSTRAINT FK_5C6B2EFDA76ED395');
        $this->addSql('ALTER TABLE Denomination DROP CONSTRAINT FK_D9F7AF44272FC9F');
        $this->addSql('ALTER TABLE Furniture DROP CONSTRAINT FK_E4AC5810443707B0');
        $this->addSql('DROP SEQUENCE Action_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ActionType_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Alert_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ArtWorkLog_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Attachment_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Author_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE AuthorType_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Building_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Commune_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Correspondent_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Denomination_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Departement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE DepositType_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Depositor_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE EntryMode_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Era_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Establishment_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE EstablishmentType_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Furniture_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Location_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE LocationType_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE MaterialTechnique_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Ministry_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Movement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE MovementActionType_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE MovementType_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE PropertyStatusCategory_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Region_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Report_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ReportSubType_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ReportType_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Responsible_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Room_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Service_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Site_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Style_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE SubDivision_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE Type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE User_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE domaine_id_seq CASCADE');
        $this->addSql('DROP TABLE Action');
        $this->addSql('DROP TABLE action_movement');
        $this->addSql('DROP TABLE ActionType');
        $this->addSql('DROP TABLE Alert');
        $this->addSql('DROP TABLE ArtWork');
        $this->addSql('DROP TABLE ArtWorkLog');
        $this->addSql('DROP TABLE Attachment');
        $this->addSql('DROP TABLE Author');
        $this->addSql('DROP TABLE AuthorType');
        $this->addSql('DROP TABLE Building');
        $this->addSql('DROP TABLE Commune');
        $this->addSql('DROP TABLE Correspondent');
        $this->addSql('DROP TABLE Denomination');
        $this->addSql('DROP TABLE denomination_materialtechnique');
        $this->addSql('DROP TABLE Departement');
        $this->addSql('DROP TABLE DepositStatus');
        $this->addSql('DROP TABLE DepositType');
        $this->addSql('DROP TABLE Depositor');
        $this->addSql('DROP TABLE EntryMode');
        $this->addSql('DROP TABLE Era');
        $this->addSql('DROP TABLE Establishment');
        $this->addSql('DROP TABLE EstablishmentType');
        $this->addSql('DROP TABLE Furniture');
        $this->addSql('DROP TABLE furniture_author');
        $this->addSql('DROP TABLE Location');
        $this->addSql('DROP TABLE LocationType');
        $this->addSql('DROP TABLE MaterialTechnique');
        $this->addSql('DROP TABLE Ministry');
        $this->addSql('DROP TABLE Movement');
        $this->addSql('DROP TABLE movement_correspondent');
        $this->addSql('DROP TABLE MovementActionType');
        $this->addSql('DROP TABLE MovementType');
        $this->addSql('DROP TABLE OfficeFurniture');
        $this->addSql('DROP TABLE PropertyStatus');
        $this->addSql('DROP TABLE PropertyStatusCategory');
        $this->addSql('DROP TABLE Region');
        $this->addSql('DROP TABLE Report');
        $this->addSql('DROP TABLE ReportSubType');
        $this->addSql('DROP TABLE ReportType');
        $this->addSql('DROP TABLE Responsible');
        $this->addSql('DROP TABLE responsible_building');
        $this->addSql('DROP TABLE Room');
        $this->addSql('DROP TABLE Service');
        $this->addSql('DROP TABLE Site');
        $this->addSql('DROP TABLE Status');
        $this->addSql('DROP TABLE Style');
        $this->addSql('DROP TABLE SubDivision');
        $this->addSql('DROP TABLE Type');
        $this->addSql('DROP TABLE "User"');
        $this->addSql('DROP TABLE domaine');
    }
}
